import Head from 'next/head'
import {Inter} from "@next/font/google";

// Import Components
import VendingMachine from '@/components/VendingMachine'
import NavBar from "@/components/NavBar";
import Grid2 from "@mui/material/Unstable_Grid2";


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Vending Machine</title>
        <meta name="Choose an item from vending" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid2 container justifyContent='center' alignItems='center' spacing={2} style={{height: '100vh', textAlign: 'center'}} >
      <main className='App'>

          <VendingMachine  />
          <NavBar />

      </main>
      </Grid2>
    </>
  )
}
