import Head from 'next/head'
import Image from 'next/image'
import {Inter} from "@next/font/google";
import Link from 'next/link'
import '@/styles/Chips.module.css'

// Import Components
import VendingMachine from '@/pages/VendingMachine'
import NavBar from "@/pages/NavBar";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Vending Machine</title>
        <meta name="Choose an item from vending" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='App'>
        <VendingMachine />
        <NavBar />
      </main>
    </>
  )
}
