import Head from "next/head";
import styles from "@/styles/Home.module.css";

import MemeList from "../../components/MemeList";
import MemeForm from "../../components/MemeForm";
import rootReducer from "../../config/rootReducer";
import { Provider } from "react-redux";
import { configureStore } from "@reduxjs/toolkit";

const store = configureStore({
  reducer: rootReducer,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Provider store={store}>
          <MemeForm />
          <MemeList />
        </Provider>
      </main>
    </>
  );
}
